config/routes.rb
Rails.application.routes.draw do
  get 'pages/VR_PSVR'

  get 'pages/VR_VIVE'

  get 'pages/VR_RIFT'

  get 'pages/VR'

  get 'pages/2'

  get 'pages/2'

  get 'pages/mypage'

  devise_for :users

  resources :comments
  resources :bookmarks
  resources :pictures

  
  
  root 'site#index'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base    
    validates :title, length: { minimum: 5 }, presence: true
    validates :url, length: { minimum: 5 }, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    validates :message, presence: true
end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  helper_method :path_exists?
  
  def path_exists?(path)
      begin
          Rails.application.routes.recognize_path(path)
      rescue
          return false
      end
      
      true
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
    before_action :authenticate_user!
    before_action :set_bookmark, only: [:show, :edit, :update, :destroy]

  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @bookmarks = Bookmark.all
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      unless @bookmark = Bookmark.where(id:params[:id]).first
        flash[:alert] = 'Bookmark not found.'
        redirect_to bookmarks_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookmark_params
      params.require(:bookmark).permit(:title, :url)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def VR_PSVR
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:title, :url, :desc, :alt)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    @bookmarks = Bookmark.last(10)
    @comments = Comment.last(10)
    @picturespageone = Picture.last(2)
  end
  
    
  def path_exists?(path)
      begin
          Rails.application.routes.recognize_path(path)
      rescue
          return false
      end
      
      true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for(@bookmark) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<script type="text/javascript">headerchangebookmarks();</script>

<h1>Editing Bookmark</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<script type="text/javascript">headerchange('bookmarkslink');</script>

<h1>Listing Bookmarks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.title %></td>
        <td><a href=<%=bookmark.url%>><%= bookmark.url %></a></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookmark', new_bookmark_path %>

app/views/bookmarks/new.html.erb
<script type="text/javascript">headerchangebookmarks();</script>

<h1>New Bookmark</h1>

<%= render 'form' %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<script type="text/javascript">headerchangebookmarks();</script>

<p>
  <strong>Title:</strong>
  <%= @bookmark.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @bookmark.url %>
</p>

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>
 

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<script type="text/javascript">headerchangecomments();</script>

<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<% comments = true %>

<script type="text/javascript">headerchange('commentslink');</script>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Comments:</th>
      <th> - </th>
      <th>Time:</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.message %></td>
        <td> - </td>
        <td><%= comment.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<% if comments == true then %>
    <%= link_to 'New Comment', new_comment_path %>
<% else %>
    <p>Comments Disabled</p>
<% end %>

app/views/comments/new.html.erb
<script type="text/javascript">headerchangecomments();</script>

<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<script type="text/javascript">headerchangecomments();</script>

<p>
  <strong>Message:</strong>
  <%= @comment.message %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Destroy', @comment, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookmarks</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    </script>
  </head>
  <body>
    <ul id="header">
      <li class="header-left"><%= link_to 'Home', root_path, id: "homelink", class: "header-text header-text-active" %></li>
      <li class="header-left"><%= link_to 'Bookmarks', bookmarks_path, id: "bookmarkslink", class: "header-text" %></li>
      <li class="header-left"><%= link_to 'Comments', comments_path, id: "commentslink", class: "header-text" %></li>
      <li class="header-left"><%= link_to 'Pictures', pictures_path, id: "pictureslink", class: "header-text" %></li>
      <li class="header-left"><%= link_to 'Fonts and Font Sizes', pages_2_path, id: "fontlink", class: "header-text" %></li>
      <li class="header-left"><%= link_to 'Games running on VR', pages_VR_path, id: "vrlink", class: "header-text" %></li>
      <li class="header-left"><%= link_to 'Oculus Rift', pages_VR_RIFT_path, id: "vrriftlink", class: "header-text" %></li>
      <li class="header-left"><%= link_to 'HTC Vive', pages_VR_VIVE_path, id: "vrvivelink", class: "header-text" %></li>
      <li class="header-left"><%= link_to 'Sony PSVR', pages_VR_PSVR_path, id: "vrpsvrlink", class: "header-text" %></li>
      <% if user_signed_in? %>
        <% if path_exists?("/pages/" << current_user.id.to_s) %>
          <li class="header-left"><%= link_to 'Your Page', "/pages/" << current_user.id.to_s, id: "userpage", class: "header-text" %></li>
        <% end %>
      <% end %>
      <li class="header-right">
        <% if user_signed_in? %>
          <a id="userlink" class="header-text header-text-arrow hvr-icon-hang"><%= current_user.email %></a>
          <ul class="sub-header">
            <li><%= link_to 'Edit profile', edit_user_registration_path, class: "header-text" %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "header-text" %></li>
          </ul>
        <% else %>
          <a id="userlink" class="header-text header-text-arrow header-text-red hvr-icon-hang">Not currently signed in.</a>
          <ul class="sub-header">
            <nav id="sub-header-user-layout-out">
              <li><%= link_to "Sign up", new_user_registration_path, class: "header-text" %></li>
              <li><%= link_to "Login", new_user_session_path, class: "header-text" %></li>
            </nav>
          </ul>
        <% end %>
      </li>
    </ul>
  
    <br>
  
    <h2 style="display: inline">Welcome to my site, current time is <span id='ct' ></span> <%= Time.now.strftime("%P") %></h2>
    <script type="text/javascript">display_ct();</script>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
    <br>
    
    <%= yield %>
  </body>
</html>

app/views/pages/2.html.erb
<script type="text/javascript">headerchange('fontlink');</script>
<p style="font-size:250px">VERY BIG TEXT</p>
<p style="font-size:7px">VERY SMALL TEXT</p>
<p style="font-size:30px; font-family: monospace">^ css font sizes ^</p>


<h1>Lagest font size in html</h1>
<h2>Second largest</h2>
<h3>Third</h3>
<h4>Forth</h4>
<h5>Fifth</h5>
<h6>Smallest header size</h6>
<p>Normal text</p>

app/views/pages/VR.html.erb
<script type="text/javascript">headerchange('vrlink');</script>
<br>
<iframe width="640" height="360" src="https://www.youtube.com/embed/dPyepUMD7Lc" frameborder="0" allowfullscreen></iframe>
<iframe width="640" height="360" src="https://www.youtube.com/embed/EdHDNmiyWqo" frameborder="0" allowfullscreen></iframe>
<iframe width="640" height="360" src="https://www.youtube.com/embed/pN6YCFlS8nU" frameborder="0" allowfullscreen></iframe>
<iframe width="640" height="360" src="https://www.youtube.com/embed/EuZdHTKzXa8" frameborder="0" allowfullscreen></iframe>
<iframe width="640" height="360" src="https://www.youtube.com/embed/BWjP77TztTQ" frameborder="0" allowfullscreen></iframe>

app/views/pages/VR_PSVR.html.erb
<script type="text/javascript">headerchange('vrpsvrlink');</script>
<br>
<iframe width='640' height='360' scrolling='no' frameborder='0' src='https://www.yahoo.com/tech/playstation-virtual-reality-headset-ps4-180013718.html?format=embed' allowfullscreen='true' mozallowfullscreen='true' webkitallowfullscreen='true' allowtransparency='true'></iframe>
<iframe width="640" height="360" src="https://www.youtube.com/embed/s4b8dq8nSzY" frameborder="0" allowfullscreen></iframe>
<iframe width="640" height="360" src="https://www.youtube.com/embed/XXvBqdHrqGo" frameborder="0" allowfullscreen></iframe>
<iframe width="640" height="360" src="https://www.youtube.com/embed/kYhZEREhbsI" frameborder="0" allowfullscreen></iframe>

app/views/pages/VR_RIFT.html.erb
<script type="text/javascript">headerchange('vrriftlink');</script>
<body style="background:url('http://blogs-images.forbes.com/davidewalt/files/2016/03/oculus-rift-vr-headset-1200x698.jpg');">
<br>
<iframe width="640" height="360" src="https://www.youtube.com/embed/etv_IxVh7cc" frameborder="0" allowfullscreen></iframe>
<img src="http://cdn.arstechnica.net/wp-content/uploads/2016/03/gdc16floor-1.jpg" height="360" width="320">
<iframe width="640" height="360" src="https://www.youtube.com/embed/f79zdVmF-dM" frameborder="0" allowfullscreen></iframe>
<iframe width="640" height="360" src="https://www.youtube.com/embed/asduqdRizqs" frameborder="0" allowfullscreen></iframe>
<img src="http://core0.staticworld.net/images/article/2015/09/oculus-touch-2-100616982-orig.png" height="360" width="500"> 
<img src="http://cdn.arstechnica.net/wp-content/uploads/2016/03/gdc16floor-4.jpg" height="360" width="320">
<script height="360px" width="640px" src="http://player.ooyala.com/iframe.js#pbid=99a2372b0c174bb68d3119c6dad07d66&ec=I0OHd2dTohrKy-0w54pV9hlVT7ZwHBwn"></script>
<iframe width="640" height="360" src="https://www.youtube.com/embed/Otz5rAUOaqk" frameborder="0" allowfullscreen></iframe>
</body>

app/views/pages/VR_VIVE.html.erb
<script type="text/javascript">headerchange('vrvivelink');</script>
<br>
<iframe width="640" height="360" src="https://www.youtube.com/embed/A9pbcR-DlwE" frameborder="0" allowfullscreen></iframe>
<img src="http://cdn.arstechnica.net/wp-content/uploads/2016/03/gdc16floor-3.jpg" width ="320" height="360"/>
<iframe width="640" height="360" src="https://www.youtube.com/embed/iWproPHhHd0" frameborder="0" allowfullscreen></iframe>
<img src="http://icdn2.digitaltrends.com/image/htc-vive-pre-handson_5229-720x720.jpg" width="500" height="360"/>
<iframe width="640" height="360" src="https://www.youtube.com/embed/Otz5rAUOaqk" frameborder="0" allowfullscreen></iframe>

app/views/pages/mypage.html.erb
<h1>Pages#mypage</h1>
<p>Find me in app/views/pages/mypage.html.erb</p>

app/views/pictures/_form.html.erb
<%= simple_form_for(@picture) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :url %>
    <%= f.input :desc %>
    <%= f.input :alt %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<script type="text/javascript">headerchange('pictureslink');</script>

<h1>Latest Pictures</h1>

<div style="layout: block;">
<table style="float: left">
  <tbody>
    <tr>
      <% @pictures.each do |picture| %>
        <td>
          <div class="image">
            <a href=<%= picture.url %>>
              <img src=<%= picture.url %> alt=<%= picture.alt %> width="300" height="200">
            </a>
            <div class="image-desc"><%= picture.desc %></div>
          </div>
        </td>
      <% end %>
    </tr>
  </tbody>
</table>
</div>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p>
  <strong>Url:</strong>
  <%= @picture.url %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @picture.desc %>
</p>

<p>
  <strong>Alt:</strong>
  <%= @picture.alt %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>

app/views/site/index.html.erb
<br>
<br>

<table style="float: left">
  <thead>
    <tr>
      <th style="font-size:large;">Latest Bookmarks</th>
    </tr>
  </thead>
  
  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= link_to bookmark.title, bookmark.url %></td>
      </tr>
    <% end %>
  </body>
</table>

<table style="float: left">
  <thead>
    <tr>
      <th style="font-size:large;">Latest Messages</th>
    </tr>
  </thead>
  
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.message %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<table style="float: left">
  <thead>
    <tr>
      <th style="font-size:large;">Latest Pictures</th>
    </tr>
  </thead>
  
  <tbody>
    <tr>
      <% @picturespageone.each do |picture| %>
        <td>
          <div style="float: left; width: 250px;">
            <a href=<%= picture.url %>>
              <img style="width: 100%; height: auto;" src=<%= picture.url %> alt=<%= picture.alt %>>
            </a>
          </div>
        </td>
      <% end %>
    </tr>
  </tbody>
</table>